import HomeView from "@/components/views/Home";
import Head from "next/head";

const HomePage = () => {
  return (
    <>
      <Head>
        <title>Holly Beast Store</title>
      </Head>
      <HomeView />
    </>
  );
};

export default HomePage;

// import Head from "next/head";

// export default function Home() {
//   return (
//     <>
//       <Head>
//         <title>Holly Beast Store</title>
//         <meta name="description" content="Generated by create next app" />
//         <meta name="viewport" content="width=device-width, initial-scale=1" />
//         <link rel="icon" href="/favicon.ico" />
//       </Head>
//       <main>
//         <h1>Hello</h1>
//       </main>
//     </>
//   );
// }
